name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - master

jobs:
  #shell:
  #  runs-on:ubuntu-latest
  #  steps:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: edencoania/release:hello_github_actions-${{ github.sha }}
      
            #- name: Build and push
        #uses: docker/build-push-action@v5
          #with:
          # push: true
            #      tags: edencoania/release:hello_actions-${{ env.VERSION }}
     
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: edencoania/release:hello_actions-latest
      
        
      - name: Run shell commands
        run: |
          ssh -i ${{secrets.SSH_PRIVATE_KEY}} ubuntu@13.57.56.220 "pkill -9 python3 && python3 app.py"
