name: Generate
 
on: 
  push:
    branches:
      - master


jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@v3

    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit



